apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf-client
  namespace: client
  labels:
    app:  bsf
    role: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  bsf
      role: client
  template:
    metadata:
      labels:
        app:  bsf
        role: client
    spec:
      containers:
      - name: app
        image: eu.gcr.io/bsf-studio/bsf-client:{{VERSION}}
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name:  PORT
            value: '8080'

---

kind: Service
apiVersion: v1
metadata:
  name: bsf-client
  namespace: client
spec:
  type: LoadBalancer
  selector:
    app:  bsf
    role: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080