apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf_client-ru
  labels:
    app: bsf_client-ru
    environment: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bsf_client-ru
  template:
    metadata:
      labels:
        app: bsf_client-ru
        environment: staging
    spec:
      containers:
      - name: bsf_client-ru
        image: eu.gcr.io/teak-sunup-126712/bsf_client/bsf_client-ru:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
      imagePullSecrets:
      - name: gcr-json-key
---
kind: Service
apiVersion: v1
metadata:
  name: bsf_client-ru
  labels:
    app: bsf_client-ru
    environment: staging
spec:
  selector:
    app: bsf_client-ru
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bsf_client-ru
  labels:
    app: bsf_client-ru
    environment: staging
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - staging.bsf_client.ru
      secretName: bsf_client-ru-staging-crt
  rules:
  - host: staging.bsf_client.ru
    http:
      paths:
      - path: /
        backend:
          serviceName: bsf_client-ru
          servicePort: 80
